### ISSUE TITLE
Extra steps needed to compile for Debian

### ISSUE THREAD

**Issue by Karel-van-de-Plassche** [sflow/sflowtool#2]
To compile for Debian

```
$ uname -a
Linux xxxxxxxxxxxx 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux
```

I had to do

```
aclocal
automake
automake --add-missing
autoconf
./configure
make
make install
```

Is this intended, and if so, could this be added to the README?

**Comment by rowanthorpe** [comment]
@Karel-van-de-Plassche I wrote and have (independently) maintained [Debian packaging](https://github.com/rowanthorpe/sflowtool-debian) for this for a while, and until I last looked at it I remember autoreconf (as a shorthand for the pre-make steps you took) worked quite seamlessly. I agree it would be helpful to mention that in the upstream README.

BTW: Most of the fixes I've made in my repo have been cherrypicked into upstream over time (mostly pre-github), but there are still [a few patches there that weren't used](https://github.com/rowanthorpe/sflowtool-debian/tree/master/debian/patches) (mostly Debian-specific ones, and some more pedantic/stylistic than necessary - so not surprisingly unused - but which I've left there for now because they helped when finding more important bugs).

FYI @sflow , I am presently battling a monster TODO-list, so am still sitting on several half-finished/uncommitted tweaks to synch the packaging with the latest upstream version-bump (and a couple of upstream-bugfixes and a few more ipv6 feature-bumps, which I will try to PR sometime soon). I now don't get to use sflowtool regularly due to a change of employment, and also after 2.5 years no Debian Developers ever stepped up to mentor the package into the Debian distro, which unfortunately increases the effort-to-reward ratio for that too... :-/

**Comment by binBASH** [comment]
Can confirm that I had to do the extra steps on my Ubuntu 14.04, too

**Comment by sflow** [comment]
I added boot.sh (which calls "autoreconf --install --force") and changed the instructions to build from sources so that it looks like this:

./boot.sh
./configure
make
sudo make install

This works for me on Ubuntu 12.04.5 (Debian Wheezy),  so I'll close this issue.  But please open another if there are any problems.
