### ISSUE TITLE
 Questions about sFlow Optical Interface Structures

### ISSUE THREAD

**Issue by andy8408** [sflow/sflowtool#36]
I have some questions about the definition of the SFP counter Sample in sFlow Optical Interface Structures.
According to https://sflow.org/sflow_optics.txt,  The information of SFP is defined as follows:

struct lane {
  unsigned int index; /* 1-based index of lane within module, 0=unknown */
  unsigned int tx_bias_current; /* microamps */
  unsigned int tx_power;        /* microwatts */
  unsigned int tx_power_min;    /* microwatts */
  unsigned int tx_power_max;    /* microwatts */
  unsigned int tx_wavelength;   /* nanometers */
  unsigned int rx_power;        /* microwatts */
  unsigned int rx_power_min;    /* microwatts */
  unsigned int rx_power_max;    /* microwatts */
  unsigned int rx_wavelength;   /* nanometers */
}

/* Optical SFP / QSFP metrics */
/* opaque = counter_data; enterprise=0; format=10 */
struct sfp {
  unsigned int module_id;
  unsigned int module_num_lanes;      /* total number of lanes in module */
  unsigned int module_supply_voltage; /* millivolts */
  int module_temperature;             /* thousandths of a degree Celsius */
  lane<> lanes;
}

However, According to the definition in sflowtool, there is an extra num_lanes for the definition of SFP information.  This make us confused, it conflicts with the definition in https://sflow.org/sflow_optics.txt. Logically, module_total_lanes has already defined the number of lanes. Is it meaningless to add num_lanes?
I want to confirm whether the definition of Optical SFP in sflowTool is wrong? I look forward to your reply. Thanks.

/* Optical SFP/QSFP metrics */
/* opaque = counter_data; enterprise = 0; format = 10 */

typedef struct {
  uint32_t lane_index;      /* index of lane in module - starting from 1 */
  uint32_t tx_bias_current; /* microamps */
  uint32_t tx_power;        /* microwatts */
  uint32_t tx_power_min;    /* microwatts */
  uint32_t tx_power_max;    /* microwatts */
  uint32_t tx_wavelength;   /* nanometers */
  uint32_t rx_power;        /* microwatts */
  uint32_t rx_power_min;    /* microwatts */
  uint32_t rx_power_max;    /* microwatts */
  uint32_t rx_wavelength;   /* nanometers */
} SFLLane;

typedef struct {
  uint32_t module_id;
  uint32_t module_total_lanes; /* total lanes in module */
  uint32_t module_supply_voltage; /* millivolts */
  int32_t module_temperature; /* signed - in oC / 1000 */
 uint32_t num_lanes; /* number of active lane structs to come */   ===== Why add the definition of this field
  SFLLane *lanes;
} SFLSFP_counters;

**Comment by sflow** [comment]
The XDR notation "lane<> lines" indicates an array.  That means the on-the-wire encoding will have a 32-bit field indicating the number of elements in the array,  followed by the elements.   It's convenient for the equivalent C structure to make that explicit.  It may be redundant for the reasons you state,  but that's something to be cross-checked later.  Make sense?

I hope you find the optical counters easy to use / populate.  They can be very helpful.  A window into the physical world. A change in rx_power can mean that the transceiver is degrading and should be replaced preemptively,  or that someone on a skateboard used an exposed cable to help them swing round a corner, and so on.

**Comment by andy8408** [comment]
I understand your explanation.  However, the addition or reduction of a field in the packet causes the sFlow agent and sFlow collector to not work normally on the optical counters. Looking forward to your confirmation results after cross-checked, thanks.

**Comment by sflow** [comment]
Not quite sure what your concern is here.  Perhaps I should point out that this particular C structure is only used for decoding sFlow,  not encoding.   While you *could* use a C structure to encode an sFlow structure and then memcpy() it straight into the output buffer,  the fact that everything has to be in network byte order typically means that fields are encoded one at a time.  Here is an example of a routine that encodes the optical lane data:

https://github.com/sflow/host-sflow/blob/master/src/sflow/sflow_receiver.c#L613-L633

Does this reassure you?  Or have I missed something?

**Comment by andy8408** [comment]
What I care about is whether the ‘num_lanes’ field needs to be included in Optical Interface Structures (this field is not explicitly required in https://sflow.org/sflow_optics.txt.). If the implementation of sFlow agent and sFlow collector are inconsistent, it will cause the collector cannot decoding counter samples with optical information(There may be many sflow agent and sflow collector providers.). For example, if the packet sent by the sFlow agent does not contain the num_lanes field, there will be errors while using sflow-tool to decode the sFlow packet, , but if another sflow collector thinks No need for ‘num_lanes’, it will think this sFlow packet is correct.

**Comment by sflow** [comment]
I think your discomfort with this might be due to a misunderstanding:  the structure defined in the sFlow spec is an XDR structure.  Not a C structure.  The sFlow standard uses XDR for the spec, which also determines the wire-encoding.

XDR is a mature standard that Sun Microsystems developed for RPC / NFS many years ago:
https://en.wikipedia.org/wiki/External_Data_Representation

For example. This structure in the sFlow optical spec is written in XDR:

struct sfp {
  unsigned int module_id;
  unsigned int module_num_lanes;      /* total number of lanes in module */
  unsigned int module_supply_voltage; /* millivolts */
  int module_temperature;             /* thousandths of a degree Celsius */
  lane<> lanes;
}

The notation "lane<> lanes" denotes a variable length XDR array.  Which means the wire encoding of that field must start with a 32-bit integer in network byte order indicating the number of elements in the array.

The XDR standard is a good fit for sFlow.  It is strictly quad-aligned for performance, and network-byte-order for portability. It can express variable length arrays and optional elements without ambiguity.  If you were choosing today between XDR, Google Protocol Buffers, JSON, BSON etc. I believe XDR would still be the right answer.

There are XDR compilers out there that will generate C code to encode and decode structures, but for sFlow there are only a handful of structures to encode/decode so doing it "by hand" is OK.  It was convenient for sflowtool to define some C structures that correspond approximately to the XDR structures but it didn't have to be done that way at all.

I hope this is clear.  I'll close the issue for now, but please reopen if there is any lingering doubt.
